apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: keda-demo
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: keda-demo
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  namespaceSelector:
    any: true
  endpoints:
  - port: http